pipeline {
    agent any

    environment {
        IMAGE = "pranavpatildevops/eks-app:${BUILD_NUMBER}"
    }

    stages {

        stage('Build') {
            steps {
                sh 'docker build -t $IMAGE .'
            }
        }

        stage('Push') {
            steps {
                sh 'docker push $IMAGE'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                sed -i "s|latest|${BUILD_NUMBER}|g" k8s/base/deployment.yaml
                kubectl apply -f k8s/
                '''
            }
        }

        stage('Rollback if Failed') {
            steps {
                sh 'kubectl rollout status deployment/eks-app || kubectl rollout undo deployment/eks-app'
            }
        }
    }
}
