pipeline {
    agent any

    environment {
        IMAGE = "pranavpatildevops/eks-app:${BUILD_NUMBER}"
    }

    stages {

        stage('Build') {
            steps {
                sh 'docker build -t $IMAGE .'
            }
        }

        stage('Push') {
            steps {
                sh 'docker push $IMAGE'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                aws eks update-kubeconfig --region ap-south-1 --name pranav-prod-eks
                cd k8s/overlays/prod
                kustomize edit set image pranavpatildevops/eks-app=$IMAGE
                kubectl apply -k .
                '''
            }
        }

        stage('Rollback if Failed') {
            steps {
                sh 'kubectl rollout status deployment/prod-eks-app || kubectl rollout undo deployment/prod-eks-app'
            }
        }
    }
}
